### ISSUE TITLE
Test for overflow:hidden, white-space: nowrap, and a floating child element

### ISSUE THREAD

**Issue by behrangsa** [w3c/csswg-test#839]
Hi all,

I have noticed that the following style+markup is rendered differently on Chrome vs Firefox. Safari renders it like Chrome. IE 11 also renders it like Chrome.

``` css
.test {
  border: 1px solid black;
  width: 200px;
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
}

.more {
  float: right;
}
```

``` html
<div class="test">
  <span class="more">More</span>
  Lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum   
</div>
```

The live demo is accessible from here:

http://codepen.io/behrangsa/pen/gaOoBq

Here is how this gets rendered in Chrome:

![Chrome rendition](https://cloud.githubusercontent.com/assets/18451/9603466/4bad47f2-50f4-11e5-92de-d7d37d56a1ce.png)

And here's how it gets rendered in FF:

![Firefox rendition](https://cloud.githubusercontent.com/assets/18451/9603514/6e5b8688-50f4-11e5-9547-27364f123eb6.png)

As you can see, in Chrome the floating span pushes the content and does not go on top of the content. But in FF, the content creeps under the floating element.
